(cl:in-package span_pose-msg)
(cl:export '(HEADER-VAL
          HEADER
          VER-VAL
          VER
          SEC-VAL
          SEC
          USEC-VAL
          USEC
          LAT-VAL
          LAT
          LON-VAL
          LON
          NORTH-VAL
          NORTH
          EAST-VAL
          EAST
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          VEL-VAL
          VEL
          NSAT-VAL
          NSAT
          INS_STAT-VAL
          INS_STAT
          SOL-VAL
          SOL
          POS-VAL
          POS
          INS_STR-VAL
          INS_STR
          SOL_STR-VAL
          SOL_STR
          POS_STR-VAL
          POS_STR
))