// Generated by gencpp from file navigation/nav_status.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_NAV_STATUS_H
#define NAVIGATION_MESSAGE_NAV_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace navigation
{
template <class ContainerAllocator>
struct nav_status_
{
  typedef nav_status_<ContainerAllocator> Type;

  nav_status_()
    : header()
    , start_north(0.0)
    , start_east(0.0)
    , goal_north(0.0)
    , goal_east(0.0)
    , la_north(0.0)
    , la_east(0.0)
    , state(0)  {
    }
  nav_status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , start_north(0.0)
    , start_east(0.0)
    , goal_north(0.0)
    , goal_east(0.0)
    , la_north(0.0)
    , la_east(0.0)
    , state(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _start_north_type;
  _start_north_type start_north;

   typedef double _start_east_type;
  _start_east_type start_east;

   typedef double _goal_north_type;
  _goal_north_type goal_north;

   typedef double _goal_east_type;
  _goal_east_type goal_east;

   typedef double _la_north_type;
  _la_north_type la_north;

   typedef double _la_east_type;
  _la_east_type la_east;

   typedef uint32_t _state_type;
  _state_type state;




  typedef boost::shared_ptr< ::navigation::nav_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::nav_status_<ContainerAllocator> const> ConstPtr;

}; // struct nav_status_

typedef ::navigation::nav_status_<std::allocator<void> > nav_status;

typedef boost::shared_ptr< ::navigation::nav_status > nav_statusPtr;
typedef boost::shared_ptr< ::navigation::nav_status const> nav_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::nav_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::nav_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'navigation': ['/home/bikramjothanzra/recboat-ros/src/navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation::nav_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::nav_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::nav_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::nav_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::nav_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::nav_status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::nav_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d88d3bb1fcfc3d13a0bfef92f5caa348";
  }

  static const char* value(const ::navigation::nav_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd88d3bb1fcfc3d13ULL;
  static const uint64_t static_value2 = 0xa0bfef92f5caa348ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::nav_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/nav_status";
  }

  static const char* value(const ::navigation::nav_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::nav_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 start_north\n\
float64 start_east\n\
\n\
float64 goal_north\n\
float64 goal_east\n\
\n\
float64 la_north\n\
float64 la_east\n\
\n\
uint32 state\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::navigation::nav_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::nav_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.start_north);
      stream.next(m.start_east);
      stream.next(m.goal_north);
      stream.next(m.goal_east);
      stream.next(m.la_north);
      stream.next(m.la_east);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct nav_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::nav_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::nav_status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "start_north: ";
    Printer<double>::stream(s, indent + "  ", v.start_north);
    s << indent << "start_east: ";
    Printer<double>::stream(s, indent + "  ", v.start_east);
    s << indent << "goal_north: ";
    Printer<double>::stream(s, indent + "  ", v.goal_north);
    s << indent << "goal_east: ";
    Printer<double>::stream(s, indent + "  ", v.goal_east);
    s << indent << "la_north: ";
    Printer<double>::stream(s, indent + "  ", v.la_north);
    s << indent << "la_east: ";
    Printer<double>::stream(s, indent + "  ", v.la_east);
    s << indent << "state: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_NAV_STATUS_H
