// Generated by gencpp from file navigation/nav_wpt.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_NAV_WPT_H
#define NAVIGATION_MESSAGE_NAV_WPT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace navigation
{
template <class ContainerAllocator>
struct nav_wpt_
{
  typedef nav_wpt_<ContainerAllocator> Type;

  nav_wpt_()
    : header()
    , north(0.0)
    , east(0.0)
    , vel(0.0)
    , action(0)  {
    }
  nav_wpt_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , north(0.0)
    , east(0.0)
    , vel(0.0)
    , action(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _north_type;
  _north_type north;

   typedef double _east_type;
  _east_type east;

   typedef float _vel_type;
  _vel_type vel;

   typedef uint32_t _action_type;
  _action_type action;




  typedef boost::shared_ptr< ::navigation::nav_wpt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::nav_wpt_<ContainerAllocator> const> ConstPtr;

}; // struct nav_wpt_

typedef ::navigation::nav_wpt_<std::allocator<void> > nav_wpt;

typedef boost::shared_ptr< ::navigation::nav_wpt > nav_wptPtr;
typedef boost::shared_ptr< ::navigation::nav_wpt const> nav_wptConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::nav_wpt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::nav_wpt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'navigation': ['/home/bikramjothanzra/recboat-ros/src/navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation::nav_wpt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::nav_wpt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::nav_wpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::nav_wpt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::nav_wpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::nav_wpt_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::nav_wpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09baa8a35c67a0a28096eac554dd6379";
  }

  static const char* value(const ::navigation::nav_wpt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09baa8a35c67a0a2ULL;
  static const uint64_t static_value2 = 0x8096eac554dd6379ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::nav_wpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/nav_wpt";
  }

  static const char* value(const ::navigation::nav_wpt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::nav_wpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 north\n\
float64 east\n\
\n\
float32 vel\n\
\n\
uint32 action\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::navigation::nav_wpt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::nav_wpt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.north);
      stream.next(m.east);
      stream.next(m.vel);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct nav_wpt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::nav_wpt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::nav_wpt_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "north: ";
    Printer<double>::stream(s, indent + "  ", v.north);
    s << indent << "east: ";
    Printer<double>::stream(s, indent + "  ", v.east);
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
    s << indent << "action: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_NAV_WPT_H
