(cl:in-package vcu_relay-msg)
(cl:export '(HEADER-VAL
          HEADER
          VER-VAL
          VER
          SEC-VAL
          SEC
          USEC-VAL
          USEC
          STATE-VAL
          STATE
          PORT_THROTTLE-VAL
          PORT_THROTTLE
          STBD_THROTTLE-VAL
          STBD_THROTTLE
          PORT_SHIFT-VAL
          PORT_SHIFT
          STBD_SHIFT-VAL
          STBD_SHIFT
          PORT_THROTTLE_OUT-VAL
          PORT_THROTTLE_OUT
          STBD_THROTTLE_OUT-VAL
          STBD_THROTTLE_OUT
          STEER_ANGLE-VAL
          STEER_ANGLE
          HCI_SWITCH-VAL
          HCI_SWITCH
          PORT_IND-VAL
          PORT_IND
          STBD_IND-VAL
          STBD_IND
          REMOTE_SELECT-VAL
          REMOTE_SELECT
          AUTOLED-VAL
          AUTOLED
          HAVE_CTRL-VAL
          HAVE_CTRL
          STEER_ANGLE_REQ-VAL
          STEER_ANGLE_REQ
          STEER_MODE-VAL
          STEER_MODE
          RT_AMPS-VAL
          RT_AMPS
          RT_BAMPS-VAL
          RT_BAMPS
          RT_FF-VAL
          RT_FF
          RT_FM-VAL
          RT_FM
          RT_FS-VAL
          RT_FS
          RT_POWER-VAL
          RT_POWER
          RT_TEMP-VAL
          RT_TEMP
          RT_VOLT-VAL
          RT_VOLT
))