#!/usr/bin/env python

'''
USAGE: ./map-smoothening 75 75
'''

# Import the required modules
import cv2
import sys

def main(x, y):
	# Load the image as grayascale
	im = cv2.imread("im_logical.bmp", cv2.IMREAD_GRAYSCALE)

	# Blur the image
	im_blur = cv2.blur(im, (x, y))
	im_blur[im==255] = 255

	# Display the image
	cv2.namedWindow("Image", cv2.WINDOW_NORMAL)
	cv2.namedWindow("Blurred Image", cv2.WINDOW_NORMAL)
	cv2.imshow("Image", im)
	cv2.imshow("Blurred Image", im_blur)
	cv2.imwrite("im_logical-new.bmp", im_blur)
	cv2.waitKey(0)

if __name__ == "__main__":
	if len(sys.argv) == 2:
		main(int(sys.argv[1]), int(sys.argv[1]))
	elif len(sys.argv) == 3:
		main(int(sys.argv[1]), int(sys.argv[2]))
	else:
		print "Argument(s) Error"
