#!/usr/bin/env python

'''
USAGE: ./map-smoothening im_logical.bmp 75 75
'''

# Import the required modules
import cv2
import sys

def main(path ,x, y):
	# Load the image as grayascale
	im = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

	# Blur the image
	im_blur = cv2.blur(im, (x, y))
	# Remove the blur in the white region
	im_blur[im==255] = 255

	# Save the blurred image
	cv2.imwrite("im_logical-new.bmp", im_blur)

	# Display the image
	cv2.namedWindow("Image", cv2.WINDOW_NORMAL)
	cv2.namedWindow("Blurred Image", cv2.WINDOW_NORMAL)
	cv2.imshow("Image", im)
	cv2.imshow("Blurred Image", im_blur)
	cv2.waitKey(0)

if __name__ == "__main__":
	if len(sys.argv) == 3:
		main(sys.argv[1], int(sys.argv[2]), int(sys.argv[2]))
	elif len(sys.argv) == 4:
		main(sys.argv[1], int(sys.argv[2]), int(sys.argv[3]))
	else:
		print "Argument(s) Error"
